function [ks] = assemashell(mesh,pdecoef, matprop, signatures)%(p_shell,t,C,lambda,localcoordinates,A,long,signatures)

% Take values from mesh struct

    nt = mesh.nt;
    np = mesh.np;
    N = mesh.N;
    t= mesh.t;


% Corner point indices

    it1=t(1,:);
    it2=t(2,:);
    it3=t(3,:);

%%
%Data processing
%Build ID array
    ID=zeros(6,np);
    ID(1,1:np)=1:np;         %DOF 1: X, longitudinal displacement
    ID(2,1:np)=ID(1,:)+np;   %DOF 2: Y, longitudinal displacement
    ID(3,1:np)=ID(1,:)+2*np; %DOF 3: W, transversal displacement
    ID(4,1:np)=ID(1,:)+3*np; %DOF 4: theta x, rotation around x axis
    ID(5,1:np)=ID(1,:)+4*np; %DOF 5: theta y, rotation around y axis
    ID(6,1:np)=ID(1,:)+5*np; %DOF 6: theta z, rotation around z axis

    IDv1=ID(:,it1);
    IDv2=ID(:,it2);
    IDv3=ID(:,it3);

    %Build LM array
    LM=zeros(18,nt);
    LM(1:6,1:nt)=IDv1(1:6,1:nt);
    LM(7:12,1:nt)=IDv2(1:6,1:nt);
    LM(13:18,1:nt)=IDv3(1:6,1:nt);


% Rotation of elements

    lambdaxgxl = mesh.lambda.lambdaxgxl; 
    lambdaxgyl = mesh.lambda.lambdaxgyl; 
    lambdaxgzl = mesh.lambda.lambdaxgzl;

    lambdaygxl = mesh.lambda.lambdaygxl;
    lambdaygyl = mesh.lambda.lambdaygyl;
    lambdaygzl = mesh.lambda.lambdaygzl;

    lambdazgxl = mesh.lambda.lambdazgxl;
    lambdazgyl = mesh.lambda.lambdazgyl;
    lambdazgzl = mesh.lambda.lambdazgzl;

    [kdkt] = dkt_element(mesh,pdecoef);

for i = 1:9
    for j = i:9
        eval(sprintf('k%d%ddkt = kdkt.k%d%ddkt;',i,j,i,j));
    end
end


%% ANDES

    [kandes] = andes_element(mesh,pdecoef,matprop, signatures);
    
for i = 1:9
    for j = i:9
        eval(sprintf('k%d%dandes = kandes.k%d%dandes;',i,j,i,j));
    end
end
     
%% CALCULO DE LA MATRIZ GLOBAL ROTADA DE CADA ELEMENTO
 
[Keg1010]=k55dkt.*lambdaxgxl.^2+2.*k56dkt.*lambdaxgxl.*lambdaygxl+k66dkt.* ...
  lambdaygxl.^2+k66andes.*lambdazgxl.^2;
[Keg1011]=k55dkt.*lambdaxgxl.*lambdaxgyl+k56dkt.*lambdaxgyl.*lambdaygxl+k56dkt.* ...
  lambdaxgxl.*lambdaygyl+k66dkt.*lambdaygxl.*lambdaygyl+k66andes.* ...
  lambdazgxl.*lambdazgyl;
[Keg1012]=k55dkt.*lambdaxgxl.*lambdaxgzl+k56dkt.*lambdaxgzl.*lambdaygxl+k56dkt.* ...
  lambdaxgxl.*lambdaygzl+k66dkt.*lambdaygxl.*lambdaygzl+k66andes.* ...
  lambdazgxl.*lambdazgzl;
[Keg1013]=((k57dkt+k67andes).*lambdaxgxl+(k67dkt+k68andes).*lambdaygxl).* ...
  lambdazgxl;
[Keg1014]=k67andes.*lambdaxgyl.*lambdazgxl+k68andes.*lambdaygyl.*lambdazgxl+ ...
  k57dkt.*lambdaxgxl.*lambdazgyl+k67dkt.*lambdaygxl.*lambdazgyl;
[Keg1015]=k67andes.*lambdaxgzl.*lambdazgxl+k68andes.*lambdaygzl.*lambdazgxl+ ...
  k57dkt.*lambdaxgxl.*lambdazgzl+k67dkt.*lambdaygxl.*lambdazgzl;
[Keg1016]=k58dkt.*lambdaxgxl.^2+lambdaygxl.*((k59dkt+k68dkt).*lambdaxgxl+k69dkt.* ...
  lambdaygxl)+k69andes.*lambdazgxl.^2;
[Keg1017]=k58dkt.*lambdaxgxl.*lambdaxgyl+k68dkt.*lambdaxgyl.*lambdaygxl+k59dkt.* ...
  lambdaxgxl.*lambdaygyl+k69dkt.*lambdaygxl.*lambdaygyl+k69andes.* ...
  lambdazgxl.*lambdazgyl;
[Keg1018]=k58dkt.*lambdaxgxl.*lambdaxgzl+k68dkt.*lambdaxgzl.*lambdaygxl+k59dkt.* ...
  lambdaxgxl.*lambdaygzl+k69dkt.*lambdaygxl.*lambdaygzl+k69andes.* ...
  lambdazgxl.*lambdazgzl;
[Keg11]=k11andes.*lambdaxgxl.^2+2.*k12andes.*lambdaxgxl.*lambdaygxl+k22andes.* ...
  lambdaygxl.^2+k11dkt.*lambdazgxl.^2;
[Keg110]=((k15dkt+k16andes).*lambdaxgxl+(k16dkt+k26andes).*lambdaygxl).* ...
  lambdazgxl;
[Keg111]=k15dkt.*lambdaxgyl.*lambdazgxl+k16dkt.*lambdaygyl.*lambdazgxl+k16andes.* ...
  lambdaxgxl.*lambdazgyl+k26andes.*lambdaygxl.*lambdazgyl;
[Keg1111]=k55dkt.*lambdaxgyl.^2+2.*k56dkt.*lambdaxgyl.*lambdaygyl+k66dkt.* ...
  lambdaygyl.^2+k66andes.*lambdazgyl.^2;
[Keg1112]=k55dkt.*lambdaxgyl.*lambdaxgzl+k56dkt.*lambdaxgzl.*lambdaygyl+k56dkt.* ...
  lambdaxgyl.*lambdaygzl+k66dkt.*lambdaygyl.*lambdaygzl+k66andes.* ...
  lambdazgyl.*lambdazgzl;
[Keg1113]=k57dkt.*lambdaxgyl.*lambdazgxl+k67dkt.*lambdaygyl.*lambdazgxl+k67andes.* ...
  lambdaxgxl.*lambdazgyl+k68andes.*lambdaygxl.*lambdazgyl;
[Keg1114]=((k57dkt+k67andes).*lambdaxgyl+(k67dkt+k68andes).*lambdaygyl).* ...
  lambdazgyl;
[Keg1115]=k67andes.*lambdaxgzl.*lambdazgyl+k68andes.*lambdaygzl.*lambdazgyl+ ...
  k57dkt.*lambdaxgyl.*lambdazgzl+k67dkt.*lambdaygyl.*lambdazgzl;
[Keg1116]=k58dkt.*lambdaxgxl.*lambdaxgyl+k59dkt.*lambdaxgyl.*lambdaygxl+k68dkt.* ...
  lambdaxgxl.*lambdaygyl+k69dkt.*lambdaygxl.*lambdaygyl+k69andes.* ...
  lambdazgxl.*lambdazgyl;
[Keg1117]=k58dkt.*lambdaxgyl.^2+lambdaygyl.*((k59dkt+k68dkt).*lambdaxgyl+k69dkt.* ...
  lambdaygyl)+k69andes.*lambdazgyl.^2;
[Keg1118]=k58dkt.*lambdaxgyl.*lambdaxgzl+k68dkt.*lambdaxgzl.*lambdaygyl+k59dkt.* ...
  lambdaxgyl.*lambdaygzl+k69dkt.*lambdaygyl.*lambdaygzl+k69andes.* ...
  lambdazgyl.*lambdazgzl;
[Keg112]=k15dkt.*lambdaxgzl.*lambdazgxl+k16dkt.*lambdaygzl.*lambdazgxl+k16andes.* ...
  lambdaxgxl.*lambdazgzl+k26andes.*lambdaygxl.*lambdazgzl;
[Keg113]=k17andes.*lambdaxgxl.^2+lambdaygxl.*((k18andes+k27andes).*lambdaxgxl+ ...
  k28andes.*lambdaygxl)+k17dkt.*lambdazgxl.^2;
[Keg114]=k17andes.*lambdaxgxl.*lambdaxgyl+k27andes.*lambdaxgyl.*lambdaygxl+ ...
  k18andes.*lambdaxgxl.*lambdaygyl+k28andes.*lambdaygxl.*lambdaygyl+ ...
  k17dkt.*lambdazgxl.*lambdazgyl;
[Keg115]=k17andes.*lambdaxgxl.*lambdaxgzl+k27andes.*lambdaxgzl.*lambdaygxl+ ...
  k18andes.*lambdaxgxl.*lambdaygzl+k28andes.*lambdaygxl.*lambdaygzl+ ...
  k17dkt.*lambdazgxl.*lambdazgzl;
[Keg116]=((k18dkt+k19andes).*lambdaxgxl+(k19dkt+k29andes).*lambdaygxl).* ...
  lambdazgxl;
[Keg117]=k18dkt.*lambdaxgyl.*lambdazgxl+k19dkt.*lambdaygyl.*lambdazgxl+k19andes.* ...
  lambdaxgxl.*lambdazgyl+k29andes.*lambdaygxl.*lambdazgyl;
[Keg118]=k18dkt.*lambdaxgzl.*lambdazgxl+k19dkt.*lambdaygzl.*lambdazgxl+k19andes.* ...
  lambdaxgxl.*lambdazgzl+k29andes.*lambdaygxl.*lambdazgzl;
[Keg12]=k11andes.*lambdaxgxl.*lambdaxgyl+k12andes.*lambdaxgyl.*lambdaygxl+ ...
  k12andes.*lambdaxgxl.*lambdaygyl+k22andes.*lambdaygxl.*lambdaygyl+ ...
  k11dkt.*lambdazgxl.*lambdazgyl;
[Keg1212]=k55dkt.*lambdaxgzl.^2+2.*k56dkt.*lambdaxgzl.*lambdaygzl+k66dkt.* ...
  lambdaygzl.^2+k66andes.*lambdazgzl.^2;
[Keg1213]=k57dkt.*lambdaxgzl.*lambdazgxl+k67dkt.*lambdaygzl.*lambdazgxl+k67andes.* ...
  lambdaxgxl.*lambdazgzl+k68andes.*lambdaygxl.*lambdazgzl;
[Keg1214]=k57dkt.*lambdaxgzl.*lambdazgyl+k67dkt.*lambdaygzl.*lambdazgyl+k67andes.* ...
  lambdaxgyl.*lambdazgzl+k68andes.*lambdaygyl.*lambdazgzl;
[Keg1215]=((k57dkt+k67andes).*lambdaxgzl+(k67dkt+k68andes).*lambdaygzl).* ...
  lambdazgzl;
[Keg1216]=k58dkt.*lambdaxgxl.*lambdaxgzl+k59dkt.*lambdaxgzl.*lambdaygxl+k68dkt.* ...
  lambdaxgxl.*lambdaygzl+k69dkt.*lambdaygxl.*lambdaygzl+k69andes.* ...
  lambdazgxl.*lambdazgzl;
[Keg1217]=k58dkt.*lambdaxgyl.*lambdaxgzl+k59dkt.*lambdaxgzl.*lambdaygyl+k68dkt.* ...
  lambdaxgyl.*lambdaygzl+k69dkt.*lambdaygyl.*lambdaygzl+k69andes.* ...
  lambdazgyl.*lambdazgzl;
[Keg1218]=k58dkt.*lambdaxgzl.^2+lambdaygzl.*((k59dkt+k68dkt).*lambdaxgzl+k69dkt.* ...
  lambdaygzl)+k69andes.*lambdazgzl.^2;
[Keg13]=k11andes.*lambdaxgxl.*lambdaxgzl+k12andes.*lambdaxgzl.*lambdaygxl+ ...
  k12andes.*lambdaxgxl.*lambdaygzl+k22andes.*lambdaygxl.*lambdaygzl+ ...
  k11dkt.*lambdazgxl.*lambdazgzl;
[Keg1313]=k77andes.*lambdaxgxl.^2+2.*k78andes.*lambdaxgxl.*lambdaygxl+k88andes.* ...
  lambdaygxl.^2+k77dkt.*lambdazgxl.^2;
[Keg1314]=k77andes.*lambdaxgxl.*lambdaxgyl+k78andes.*lambdaxgyl.*lambdaygxl+ ...
  k78andes.*lambdaxgxl.*lambdaygyl+k88andes.*lambdaygxl.*lambdaygyl+ ...
  k77dkt.*lambdazgxl.*lambdazgyl;
[Keg1315]=k77andes.*lambdaxgxl.*lambdaxgzl+k78andes.*lambdaxgzl.*lambdaygxl+ ...
  k78andes.*lambdaxgxl.*lambdaygzl+k88andes.*lambdaygxl.*lambdaygzl+ ...
  k77dkt.*lambdazgxl.*lambdazgzl;
[Keg1316]=((k78dkt+k79andes).*lambdaxgxl+(k79dkt+k89andes).*lambdaygxl).* ...
  lambdazgxl;
[Keg1317]=k78dkt.*lambdaxgyl.*lambdazgxl+k79dkt.*lambdaygyl.*lambdazgxl+k79andes.* ...
  lambdaxgxl.*lambdazgyl+k89andes.*lambdaygxl.*lambdazgyl;
[Keg1318]=k78dkt.*lambdaxgzl.*lambdazgxl+k79dkt.*lambdaygzl.*lambdazgxl+k79andes.* ...
  lambdaxgxl.*lambdazgzl+k89andes.*lambdaygxl.*lambdazgzl;
[Keg14]=((k12dkt+k13andes).*lambdaxgxl+(k13dkt+k23andes).*lambdaygxl).* ...
  lambdazgxl;
[Keg1414]=k77andes.*lambdaxgyl.^2+2.*k78andes.*lambdaxgyl.*lambdaygyl+k88andes.* ...
  lambdaygyl.^2+k77dkt.*lambdazgyl.^2;
[Keg1415]=k77andes.*lambdaxgyl.*lambdaxgzl+k78andes.*lambdaxgzl.*lambdaygyl+ ...
  k78andes.*lambdaxgyl.*lambdaygzl+k88andes.*lambdaygyl.*lambdaygzl+ ...
  k77dkt.*lambdazgyl.*lambdazgzl;
[Keg1416]=k79andes.*lambdaxgyl.*lambdazgxl+k89andes.*lambdaygyl.*lambdazgxl+ ...
  k78dkt.*lambdaxgxl.*lambdazgyl+k79dkt.*lambdaygxl.*lambdazgyl;
[Keg1417]=((k78dkt+k79andes).*lambdaxgyl+(k79dkt+k89andes).*lambdaygyl).* ...
  lambdazgyl;
[Keg1418]=k78dkt.*lambdaxgzl.*lambdazgyl+k79dkt.*lambdaygzl.*lambdazgyl+k79andes.* ...
  lambdaxgyl.*lambdazgzl+k89andes.*lambdaygyl.*lambdazgzl;
[Keg15]=k12dkt.*lambdaxgyl.*lambdazgxl+k13dkt.*lambdaygyl.*lambdazgxl+k13andes.* ...
  lambdaxgxl.*lambdazgyl+k23andes.*lambdaygxl.*lambdazgyl;
[Keg1515]=k77andes.*lambdaxgzl.^2+2.*k78andes.*lambdaxgzl.*lambdaygzl+k88andes.* ...
  lambdaygzl.^2+k77dkt.*lambdazgzl.^2;
[Keg1516]=k79andes.*lambdaxgzl.*lambdazgxl+k89andes.*lambdaygzl.*lambdazgxl+ ...
  k78dkt.*lambdaxgxl.*lambdazgzl+k79dkt.*lambdaygxl.*lambdazgzl;
[Keg1517]=k79andes.*lambdaxgzl.*lambdazgyl+k89andes.*lambdaygzl.*lambdazgyl+ ...
  k78dkt.*lambdaxgyl.*lambdazgzl+k79dkt.*lambdaygyl.*lambdazgzl;
[Keg1518]=((k78dkt+k79andes).*lambdaxgzl+(k79dkt+k89andes).*lambdaygzl).* ...
  lambdazgzl;
[Keg16]=k12dkt.*lambdaxgzl.*lambdazgxl+k13dkt.*lambdaygzl.*lambdazgxl+k13andes.* ...
  lambdaxgxl.*lambdazgzl+k23andes.*lambdaygxl.*lambdazgzl;
[Keg1616]=k88dkt.*lambdaxgxl.^2+2.*k89dkt.*lambdaxgxl.*lambdaygxl+k99dkt.* ...
  lambdaygxl.^2+k99andes.*lambdazgxl.^2;
[Keg1617]=k88dkt.*lambdaxgxl.*lambdaxgyl+k89dkt.*lambdaxgyl.*lambdaygxl+k89dkt.* ...
  lambdaxgxl.*lambdaygyl+k99dkt.*lambdaygxl.*lambdaygyl+k99andes.* ...
  lambdazgxl.*lambdazgyl;
[Keg1618]=k88dkt.*lambdaxgxl.*lambdaxgzl+k89dkt.*lambdaxgzl.*lambdaygxl+k89dkt.* ...
  lambdaxgxl.*lambdaygzl+k99dkt.*lambdaygxl.*lambdaygzl+k99andes.* ...
  lambdazgxl.*lambdazgzl;
[Keg17]=k14andes.*lambdaxgxl.^2+lambdaygxl.*((k15andes+k24andes).*lambdaxgxl+ ...
  k25andes.*lambdaygxl)+k14dkt.*lambdazgxl.^2;
[Keg1717]=k88dkt.*lambdaxgyl.^2+2.*k89dkt.*lambdaxgyl.*lambdaygyl+k99dkt.* ...
  lambdaygyl.^2+k99andes.*lambdazgyl.^2;
[Keg1718]=k88dkt.*lambdaxgyl.*lambdaxgzl+k89dkt.*lambdaxgzl.*lambdaygyl+k89dkt.* ...
  lambdaxgyl.*lambdaygzl+k99dkt.*lambdaygyl.*lambdaygzl+k99andes.* ...
  lambdazgyl.*lambdazgzl;
[Keg18]=k14andes.*lambdaxgxl.*lambdaxgyl+k24andes.*lambdaxgyl.*lambdaygxl+ ...
  k15andes.*lambdaxgxl.*lambdaygyl+k25andes.*lambdaygxl.*lambdaygyl+ ...
  k14dkt.*lambdazgxl.*lambdazgyl;
[Keg1818]=k88dkt.*lambdaxgzl.^2+2.*k89dkt.*lambdaxgzl.*lambdaygzl+k99dkt.* ...
  lambdaygzl.^2+k99andes.*lambdazgzl.^2;
[Keg19]=k14andes.*lambdaxgxl.*lambdaxgzl+k24andes.*lambdaxgzl.*lambdaygxl+ ...
  k15andes.*lambdaxgxl.*lambdaygzl+k25andes.*lambdaygxl.*lambdaygzl+ ...
  k14dkt.*lambdazgxl.*lambdazgzl;
[Keg210]=k16andes.*lambdaxgyl.*lambdazgxl+k26andes.*lambdaygyl.*lambdazgxl+ ...
  k15dkt.*lambdaxgxl.*lambdazgyl+k16dkt.*lambdaygxl.*lambdazgyl;
[Keg211]=((k15dkt+k16andes).*lambdaxgyl+(k16dkt+k26andes).*lambdaygyl).* ...
  lambdazgyl;
[Keg212]=k15dkt.*lambdaxgzl.*lambdazgyl+k16dkt.*lambdaygzl.*lambdazgyl+k16andes.* ...
  lambdaxgyl.*lambdazgzl+k26andes.*lambdaygyl.*lambdazgzl;
[Keg213]=k17andes.*lambdaxgxl.*lambdaxgyl+k18andes.*lambdaxgyl.*lambdaygxl+ ...
  k27andes.*lambdaxgxl.*lambdaygyl+k28andes.*lambdaygxl.*lambdaygyl+ ...
  k17dkt.*lambdazgxl.*lambdazgyl;
[Keg214]=k17andes.*lambdaxgyl.^2+lambdaygyl.*((k18andes+k27andes).*lambdaxgyl+ ...
  k28andes.*lambdaygyl)+k17dkt.*lambdazgyl.^2;
[Keg215]=k17andes.*lambdaxgyl.*lambdaxgzl+k27andes.*lambdaxgzl.*lambdaygyl+ ...
  k18andes.*lambdaxgyl.*lambdaygzl+k28andes.*lambdaygyl.*lambdaygzl+ ...
  k17dkt.*lambdazgyl.*lambdazgzl;
[Keg216]=k19andes.*lambdaxgyl.*lambdazgxl+k29andes.*lambdaygyl.*lambdazgxl+ ...
  k18dkt.*lambdaxgxl.*lambdazgyl+k19dkt.*lambdaygxl.*lambdazgyl;
[Keg217]=((k18dkt+k19andes).*lambdaxgyl+(k19dkt+k29andes).*lambdaygyl).* ...
  lambdazgyl;
[Keg218]=k18dkt.*lambdaxgzl.*lambdazgyl+k19dkt.*lambdaygzl.*lambdazgyl+k19andes.* ...
  lambdaxgyl.*lambdazgzl+k29andes.*lambdaygyl.*lambdazgzl;
[Keg22]=k11andes.*lambdaxgyl.^2+2.*k12andes.*lambdaxgyl.*lambdaygyl+k22andes.* ...
  lambdaygyl.^2+k11dkt.*lambdazgyl.^2;
[Keg23]=k11andes.*lambdaxgyl.*lambdaxgzl+k12andes.*lambdaxgzl.*lambdaygyl+ ...
  k12andes.*lambdaxgyl.*lambdaygzl+k22andes.*lambdaygyl.*lambdaygzl+ ...
  k11dkt.*lambdazgyl.*lambdazgzl;
[Keg24]=k13andes.*lambdaxgyl.*lambdazgxl+k23andes.*lambdaygyl.*lambdazgxl+ ...
  k12dkt.*lambdaxgxl.*lambdazgyl+k13dkt.*lambdaygxl.*lambdazgyl;
[Keg25]=((k12dkt+k13andes).*lambdaxgyl+(k13dkt+k23andes).*lambdaygyl).* ...
  lambdazgyl;
[Keg26]=k12dkt.*lambdaxgzl.*lambdazgyl+k13dkt.*lambdaygzl.*lambdazgyl+k13andes.* ...
  lambdaxgyl.*lambdazgzl+k23andes.*lambdaygyl.*lambdazgzl;
[Keg27]=k14andes.*lambdaxgxl.*lambdaxgyl+k15andes.*lambdaxgyl.*lambdaygxl+ ...
  k24andes.*lambdaxgxl.*lambdaygyl+k25andes.*lambdaygxl.*lambdaygyl+ ...
  k14dkt.*lambdazgxl.*lambdazgyl;
[Keg28]=k14andes.*lambdaxgyl.^2+lambdaygyl.*((k15andes+k24andes).*lambdaxgyl+ ...
  k25andes.*lambdaygyl)+k14dkt.*lambdazgyl.^2;
[Keg29]=k14andes.*lambdaxgyl.*lambdaxgzl+k24andes.*lambdaxgzl.*lambdaygyl+ ...
  k15andes.*lambdaxgyl.*lambdaygzl+k25andes.*lambdaygyl.*lambdaygzl+ ...
  k14dkt.*lambdazgyl.*lambdazgzl;
[Keg310]=k16andes.*lambdaxgzl.*lambdazgxl+k26andes.*lambdaygzl.*lambdazgxl+ ...
  k15dkt.*lambdaxgxl.*lambdazgzl+k16dkt.*lambdaygxl.*lambdazgzl;
[Keg311]=k16andes.*lambdaxgzl.*lambdazgyl+k26andes.*lambdaygzl.*lambdazgyl+ ...
  k15dkt.*lambdaxgyl.*lambdazgzl+k16dkt.*lambdaygyl.*lambdazgzl;
[Keg312]=((k15dkt+k16andes).*lambdaxgzl+(k16dkt+k26andes).*lambdaygzl).* ...
  lambdazgzl;
[Keg313]=k17andes.*lambdaxgxl.*lambdaxgzl+k18andes.*lambdaxgzl.*lambdaygxl+ ...
  k27andes.*lambdaxgxl.*lambdaygzl+k28andes.*lambdaygxl.*lambdaygzl+ ...
  k17dkt.*lambdazgxl.*lambdazgzl;
[Keg314]=k17andes.*lambdaxgyl.*lambdaxgzl+k18andes.*lambdaxgzl.*lambdaygyl+ ...
  k27andes.*lambdaxgyl.*lambdaygzl+k28andes.*lambdaygyl.*lambdaygzl+ ...
  k17dkt.*lambdazgyl.*lambdazgzl;
[Keg315]=k17andes.*lambdaxgzl.^2+lambdaygzl.*((k18andes+k27andes).*lambdaxgzl+ ...
  k28andes.*lambdaygzl)+k17dkt.*lambdazgzl.^2;
[Keg316]=k19andes.*lambdaxgzl.*lambdazgxl+k29andes.*lambdaygzl.*lambdazgxl+ ...
  k18dkt.*lambdaxgxl.*lambdazgzl+k19dkt.*lambdaygxl.*lambdazgzl;
[Keg317]=k19andes.*lambdaxgzl.*lambdazgyl+k29andes.*lambdaygzl.*lambdazgyl+ ...
  k18dkt.*lambdaxgyl.*lambdazgzl+k19dkt.*lambdaygyl.*lambdazgzl;
[Keg318]=((k18dkt+k19andes).*lambdaxgzl+(k19dkt+k29andes).*lambdaygzl).* ...
  lambdazgzl;
[Keg33]=k11andes.*lambdaxgzl.^2+2.*k12andes.*lambdaxgzl.*lambdaygzl+k22andes.* ...
  lambdaygzl.^2+k11dkt.*lambdazgzl.^2;
[Keg34]=k13andes.*lambdaxgzl.*lambdazgxl+k23andes.*lambdaygzl.*lambdazgxl+ ...
  k12dkt.*lambdaxgxl.*lambdazgzl+k13dkt.*lambdaygxl.*lambdazgzl;
[Keg35]=k13andes.*lambdaxgzl.*lambdazgyl+k23andes.*lambdaygzl.*lambdazgyl+ ...
  k12dkt.*lambdaxgyl.*lambdazgzl+k13dkt.*lambdaygyl.*lambdazgzl;
[Keg36]=((k12dkt+k13andes).*lambdaxgzl+(k13dkt+k23andes).*lambdaygzl).* ...
  lambdazgzl;
[Keg37]=k14andes.*lambdaxgxl.*lambdaxgzl+k15andes.*lambdaxgzl.*lambdaygxl+ ...
  k24andes.*lambdaxgxl.*lambdaygzl+k25andes.*lambdaygxl.*lambdaygzl+ ...
  k14dkt.*lambdazgxl.*lambdazgzl;
[Keg38]=k14andes.*lambdaxgyl.*lambdaxgzl+k15andes.*lambdaxgzl.*lambdaygyl+ ...
  k24andes.*lambdaxgyl.*lambdaygzl+k25andes.*lambdaygyl.*lambdaygzl+ ...
  k14dkt.*lambdazgyl.*lambdazgzl;
[Keg39]=k14andes.*lambdaxgzl.^2+lambdaygzl.*((k15andes+k24andes).*lambdaxgzl+ ...
  k25andes.*lambdaygzl)+k14dkt.*lambdazgzl.^2;
[Keg410]=k25dkt.*lambdaxgxl.^2+lambdaygxl.*((k26dkt+k35dkt).*lambdaxgxl+k36dkt.* ...
  lambdaygxl)+k36andes.*lambdazgxl.^2;
[Keg411]=k25dkt.*lambdaxgxl.*lambdaxgyl+k35dkt.*lambdaxgyl.*lambdaygxl+k26dkt.* ...
  lambdaxgxl.*lambdaygyl+k36dkt.*lambdaygxl.*lambdaygyl+k36andes.* ...
  lambdazgxl.*lambdazgyl;
[Keg412]=k25dkt.*lambdaxgxl.*lambdaxgzl+k35dkt.*lambdaxgzl.*lambdaygxl+k26dkt.* ...
  lambdaxgxl.*lambdaygzl+k36dkt.*lambdaygxl.*lambdaygzl+k36andes.* ...
  lambdazgxl.*lambdazgzl;
[Keg413]=((k27dkt+k37andes).*lambdaxgxl+(k37dkt+k38andes).*lambdaygxl).* ...
  lambdazgxl;
[Keg414]=k37andes.*lambdaxgyl.*lambdazgxl+k38andes.*lambdaygyl.*lambdazgxl+ ...
  k27dkt.*lambdaxgxl.*lambdazgyl+k37dkt.*lambdaygxl.*lambdazgyl;
[Keg415]=k37andes.*lambdaxgzl.*lambdazgxl+k38andes.*lambdaygzl.*lambdazgxl+ ...
  k27dkt.*lambdaxgxl.*lambdazgzl+k37dkt.*lambdaygxl.*lambdazgzl;
[Keg416]=k28dkt.*lambdaxgxl.^2+lambdaygxl.*((k29dkt+k38dkt).*lambdaxgxl+k39dkt.* ...
  lambdaygxl)+k39andes.*lambdazgxl.^2;
[Keg417]=k28dkt.*lambdaxgxl.*lambdaxgyl+k38dkt.*lambdaxgyl.*lambdaygxl+k29dkt.* ...
  lambdaxgxl.*lambdaygyl+k39dkt.*lambdaygxl.*lambdaygyl+k39andes.* ...
  lambdazgxl.*lambdazgyl;
[Keg418]=k28dkt.*lambdaxgxl.*lambdaxgzl+k38dkt.*lambdaxgzl.*lambdaygxl+k29dkt.* ...
  lambdaxgxl.*lambdaygzl+k39dkt.*lambdaygxl.*lambdaygzl+k39andes.* ...
  lambdazgxl.*lambdazgzl;
[Keg44]=k22dkt.*lambdaxgxl.^2+2.*k23dkt.*lambdaxgxl.*lambdaygxl+k33dkt.* ...
  lambdaygxl.^2+k33andes.*lambdazgxl.^2;
[Keg45]=k22dkt.*lambdaxgxl.*lambdaxgyl+k23dkt.*lambdaxgyl.*lambdaygxl+k23dkt.* ...
  lambdaxgxl.*lambdaygyl+k33dkt.*lambdaygxl.*lambdaygyl+k33andes.* ...
  lambdazgxl.*lambdazgyl;
[Keg46]=k22dkt.*lambdaxgxl.*lambdaxgzl+k23dkt.*lambdaxgzl.*lambdaygxl+k23dkt.* ...
  lambdaxgxl.*lambdaygzl+k33dkt.*lambdaygxl.*lambdaygzl+k33andes.* ...
  lambdazgxl.*lambdazgzl;
[Keg47]=((k24dkt+k34andes).*lambdaxgxl+(k34dkt+k35andes).*lambdaygxl).* ...
  lambdazgxl;
[Keg48]=k34andes.*lambdaxgyl.*lambdazgxl+k35andes.*lambdaygyl.*lambdazgxl+ ...
  k24dkt.*lambdaxgxl.*lambdazgyl+k34dkt.*lambdaygxl.*lambdazgyl;
[Keg49]=k34andes.*lambdaxgzl.*lambdazgxl+k35andes.*lambdaygzl.*lambdazgxl+ ...
  k24dkt.*lambdaxgxl.*lambdazgzl+k34dkt.*lambdaygxl.*lambdazgzl;
[Keg510]=k25dkt.*lambdaxgxl.*lambdaxgyl+k26dkt.*lambdaxgyl.*lambdaygxl+k35dkt.* ...
  lambdaxgxl.*lambdaygyl+k36dkt.*lambdaygxl.*lambdaygyl+k36andes.* ...
  lambdazgxl.*lambdazgyl;
[Keg511]=k25dkt.*lambdaxgyl.^2+lambdaygyl.*((k26dkt+k35dkt).*lambdaxgyl+k36dkt.* ...
  lambdaygyl)+k36andes.*lambdazgyl.^2;
[Keg512]=k25dkt.*lambdaxgyl.*lambdaxgzl+k35dkt.*lambdaxgzl.*lambdaygyl+k26dkt.* ...
  lambdaxgyl.*lambdaygzl+k36dkt.*lambdaygyl.*lambdaygzl+k36andes.* ...
  lambdazgyl.*lambdazgzl;
[Keg513]=k27dkt.*lambdaxgyl.*lambdazgxl+k37dkt.*lambdaygyl.*lambdazgxl+k37andes.* ...
  lambdaxgxl.*lambdazgyl+k38andes.*lambdaygxl.*lambdazgyl;
[Keg514]=((k27dkt+k37andes).*lambdaxgyl+(k37dkt+k38andes).*lambdaygyl).* ...
  lambdazgyl;
[Keg515]=k37andes.*lambdaxgzl.*lambdazgyl+k38andes.*lambdaygzl.*lambdazgyl+ ...
  k27dkt.*lambdaxgyl.*lambdazgzl+k37dkt.*lambdaygyl.*lambdazgzl;
[Keg516]=k28dkt.*lambdaxgxl.*lambdaxgyl+k29dkt.*lambdaxgyl.*lambdaygxl+k38dkt.* ...
  lambdaxgxl.*lambdaygyl+k39dkt.*lambdaygxl.*lambdaygyl+k39andes.* ...
  lambdazgxl.*lambdazgyl;
[Keg517]=k28dkt.*lambdaxgyl.^2+lambdaygyl.*((k29dkt+k38dkt).*lambdaxgyl+k39dkt.* ...
  lambdaygyl)+k39andes.*lambdazgyl.^2;
[Keg518]=k28dkt.*lambdaxgyl.*lambdaxgzl+k38dkt.*lambdaxgzl.*lambdaygyl+k29dkt.* ...
  lambdaxgyl.*lambdaygzl+k39dkt.*lambdaygyl.*lambdaygzl+k39andes.* ...
  lambdazgyl.*lambdazgzl;
[Keg55]=k22dkt.*lambdaxgyl.^2+2.*k23dkt.*lambdaxgyl.*lambdaygyl+k33dkt.* ...
  lambdaygyl.^2+k33andes.*lambdazgyl.^2;
[Keg56]=k22dkt.*lambdaxgyl.*lambdaxgzl+k23dkt.*lambdaxgzl.*lambdaygyl+k23dkt.* ...
  lambdaxgyl.*lambdaygzl+k33dkt.*lambdaygyl.*lambdaygzl+k33andes.* ...
  lambdazgyl.*lambdazgzl;
[Keg57]=k24dkt.*lambdaxgyl.*lambdazgxl+k34dkt.*lambdaygyl.*lambdazgxl+k34andes.* ...
  lambdaxgxl.*lambdazgyl+k35andes.*lambdaygxl.*lambdazgyl;
[Keg58]=((k24dkt+k34andes).*lambdaxgyl+(k34dkt+k35andes).*lambdaygyl).* ...
  lambdazgyl;
[Keg59]=k34andes.*lambdaxgzl.*lambdazgyl+k35andes.*lambdaygzl.*lambdazgyl+ ...
  k24dkt.*lambdaxgyl.*lambdazgzl+k34dkt.*lambdaygyl.*lambdazgzl;
[Keg610]=k25dkt.*lambdaxgxl.*lambdaxgzl+k26dkt.*lambdaxgzl.*lambdaygxl+k35dkt.* ...
  lambdaxgxl.*lambdaygzl+k36dkt.*lambdaygxl.*lambdaygzl+k36andes.* ...
  lambdazgxl.*lambdazgzl;
[Keg611]=k25dkt.*lambdaxgyl.*lambdaxgzl+k26dkt.*lambdaxgzl.*lambdaygyl+k35dkt.* ...
  lambdaxgyl.*lambdaygzl+k36dkt.*lambdaygyl.*lambdaygzl+k36andes.* ...
  lambdazgyl.*lambdazgzl;
[Keg612]=k25dkt.*lambdaxgzl.^2+lambdaygzl.*((k26dkt+k35dkt).*lambdaxgzl+k36dkt.* ...
  lambdaygzl)+k36andes.*lambdazgzl.^2;
[Keg613]=k27dkt.*lambdaxgzl.*lambdazgxl+k37dkt.*lambdaygzl.*lambdazgxl+k37andes.* ...
  lambdaxgxl.*lambdazgzl+k38andes.*lambdaygxl.*lambdazgzl;
[Keg614]=k27dkt.*lambdaxgzl.*lambdazgyl+k37dkt.*lambdaygzl.*lambdazgyl+k37andes.* ...
  lambdaxgyl.*lambdazgzl+k38andes.*lambdaygyl.*lambdazgzl;
[Keg615]=((k27dkt+k37andes).*lambdaxgzl+(k37dkt+k38andes).*lambdaygzl).* ...
  lambdazgzl;
[Keg616]=k28dkt.*lambdaxgxl.*lambdaxgzl+k29dkt.*lambdaxgzl.*lambdaygxl+k38dkt.* ...
  lambdaxgxl.*lambdaygzl+k39dkt.*lambdaygxl.*lambdaygzl+k39andes.* ...
  lambdazgxl.*lambdazgzl;
[Keg617]=k28dkt.*lambdaxgyl.*lambdaxgzl+k29dkt.*lambdaxgzl.*lambdaygyl+k38dkt.* ...
  lambdaxgyl.*lambdaygzl+k39dkt.*lambdaygyl.*lambdaygzl+k39andes.* ...
  lambdazgyl.*lambdazgzl;
[Keg618]=k28dkt.*lambdaxgzl.^2+lambdaygzl.*((k29dkt+k38dkt).*lambdaxgzl+k39dkt.* ...
  lambdaygzl)+k39andes.*lambdazgzl.^2;
[Keg66]=k22dkt.*lambdaxgzl.^2+2.*k23dkt.*lambdaxgzl.*lambdaygzl+k33dkt.* ...
  lambdaygzl.^2+k33andes.*lambdazgzl.^2;
[Keg67]=k24dkt.*lambdaxgzl.*lambdazgxl+k34dkt.*lambdaygzl.*lambdazgxl+k34andes.* ...
  lambdaxgxl.*lambdazgzl+k35andes.*lambdaygxl.*lambdazgzl;
[Keg68]=k24dkt.*lambdaxgzl.*lambdazgyl+k34dkt.*lambdaygzl.*lambdazgyl+k34andes.* ...
  lambdaxgyl.*lambdazgzl+k35andes.*lambdaygyl.*lambdazgzl;
[Keg69]=((k24dkt+k34andes).*lambdaxgzl+(k34dkt+k35andes).*lambdaygzl).* ...
  lambdazgzl;
[Keg710]=((k45dkt+k46andes).*lambdaxgxl+(k46dkt+k56andes).*lambdaygxl).* ...
  lambdazgxl;
[Keg711]=k45dkt.*lambdaxgyl.*lambdazgxl+k46dkt.*lambdaygyl.*lambdazgxl+k46andes.* ...
  lambdaxgxl.*lambdazgyl+k56andes.*lambdaygxl.*lambdazgyl;
[Keg712]=k45dkt.*lambdaxgzl.*lambdazgxl+k46dkt.*lambdaygzl.*lambdazgxl+k46andes.* ...
  lambdaxgxl.*lambdazgzl+k56andes.*lambdaygxl.*lambdazgzl;
[Keg713]=k47andes.*lambdaxgxl.^2+lambdaygxl.*((k48andes+k57andes).*lambdaxgxl+ ...
  k58andes.*lambdaygxl)+k47dkt.*lambdazgxl.^2;
[Keg714]=k47andes.*lambdaxgxl.*lambdaxgyl+k57andes.*lambdaxgyl.*lambdaygxl+ ...
  k48andes.*lambdaxgxl.*lambdaygyl+k58andes.*lambdaygxl.*lambdaygyl+ ...
  k47dkt.*lambdazgxl.*lambdazgyl;
[Keg715]=k47andes.*lambdaxgxl.*lambdaxgzl+k57andes.*lambdaxgzl.*lambdaygxl+ ...
  k48andes.*lambdaxgxl.*lambdaygzl+k58andes.*lambdaygxl.*lambdaygzl+ ...
  k47dkt.*lambdazgxl.*lambdazgzl;
[Keg716]=((k48dkt+k49andes).*lambdaxgxl+(k49dkt+k59andes).*lambdaygxl).* ...
  lambdazgxl;
[Keg717]=k48dkt.*lambdaxgyl.*lambdazgxl+k49dkt.*lambdaygyl.*lambdazgxl+k49andes.* ...
  lambdaxgxl.*lambdazgyl+k59andes.*lambdaygxl.*lambdazgyl;
[Keg718]=k48dkt.*lambdaxgzl.*lambdazgxl+k49dkt.*lambdaygzl.*lambdazgxl+k49andes.* ...
  lambdaxgxl.*lambdazgzl+k59andes.*lambdaygxl.*lambdazgzl;
[Keg77]=k44andes.*lambdaxgxl.^2+2.*k45andes.*lambdaxgxl.*lambdaygxl+k55andes.* ...
  lambdaygxl.^2+k44dkt.*lambdazgxl.^2;
[Keg78]=k44andes.*lambdaxgxl.*lambdaxgyl+k45andes.*lambdaxgyl.*lambdaygxl+ ...
  k45andes.*lambdaxgxl.*lambdaygyl+k55andes.*lambdaygxl.*lambdaygyl+ ...
  k44dkt.*lambdazgxl.*lambdazgyl;
[Keg79]=k44andes.*lambdaxgxl.*lambdaxgzl+k45andes.*lambdaxgzl.*lambdaygxl+ ...
  k45andes.*lambdaxgxl.*lambdaygzl+k55andes.*lambdaygxl.*lambdaygzl+ ...
  k44dkt.*lambdazgxl.*lambdazgzl;
[Keg810]=k46andes.*lambdaxgyl.*lambdazgxl+k56andes.*lambdaygyl.*lambdazgxl+ ...
  k45dkt.*lambdaxgxl.*lambdazgyl+k46dkt.*lambdaygxl.*lambdazgyl;
[Keg811]=((k45dkt+k46andes).*lambdaxgyl+(k46dkt+k56andes).*lambdaygyl).* ...
  lambdazgyl;
[Keg812]=k45dkt.*lambdaxgzl.*lambdazgyl+k46dkt.*lambdaygzl.*lambdazgyl+k46andes.* ...
  lambdaxgyl.*lambdazgzl+k56andes.*lambdaygyl.*lambdazgzl;
[Keg813]=k47andes.*lambdaxgxl.*lambdaxgyl+k48andes.*lambdaxgyl.*lambdaygxl+ ...
  k57andes.*lambdaxgxl.*lambdaygyl+k58andes.*lambdaygxl.*lambdaygyl+ ...
  k47dkt.*lambdazgxl.*lambdazgyl;
[Keg814]=k47andes.*lambdaxgyl.^2+lambdaygyl.*((k48andes+k57andes).*lambdaxgyl+ ...
  k58andes.*lambdaygyl)+k47dkt.*lambdazgyl.^2;
[Keg815]=k47andes.*lambdaxgyl.*lambdaxgzl+k57andes.*lambdaxgzl.*lambdaygyl+ ...
  k48andes.*lambdaxgyl.*lambdaygzl+k58andes.*lambdaygyl.*lambdaygzl+ ...
  k47dkt.*lambdazgyl.*lambdazgzl;
[Keg816]=k49andes.*lambdaxgyl.*lambdazgxl+k59andes.*lambdaygyl.*lambdazgxl+ ...
  k48dkt.*lambdaxgxl.*lambdazgyl+k49dkt.*lambdaygxl.*lambdazgyl;
[Keg817]=((k48dkt+k49andes).*lambdaxgyl+(k49dkt+k59andes).*lambdaygyl).* ...
  lambdazgyl;
[Keg818]=k48dkt.*lambdaxgzl.*lambdazgyl+k49dkt.*lambdaygzl.*lambdazgyl+k49andes.* ...
  lambdaxgyl.*lambdazgzl+k59andes.*lambdaygyl.*lambdazgzl;
[Keg88]=k44andes.*lambdaxgyl.^2+2.*k45andes.*lambdaxgyl.*lambdaygyl+k55andes.* ...
  lambdaygyl.^2+k44dkt.*lambdazgyl.^2;
[Keg89]=k44andes.*lambdaxgyl.*lambdaxgzl+k45andes.*lambdaxgzl.*lambdaygyl+ ...
  k45andes.*lambdaxgyl.*lambdaygzl+k55andes.*lambdaygyl.*lambdaygzl+ ...
  k44dkt.*lambdazgyl.*lambdazgzl;
[Keg910]=k46andes.*lambdaxgzl.*lambdazgxl+k56andes.*lambdaygzl.*lambdazgxl+ ...
  k45dkt.*lambdaxgxl.*lambdazgzl+k46dkt.*lambdaygxl.*lambdazgzl;
[Keg911]=k46andes.*lambdaxgzl.*lambdazgyl+k56andes.*lambdaygzl.*lambdazgyl+ ...
  k45dkt.*lambdaxgyl.*lambdazgzl+k46dkt.*lambdaygyl.*lambdazgzl;
[Keg912]=((k45dkt+k46andes).*lambdaxgzl+(k46dkt+k56andes).*lambdaygzl).* ...
  lambdazgzl;
[Keg913]=k47andes.*lambdaxgxl.*lambdaxgzl+k48andes.*lambdaxgzl.*lambdaygxl+ ...
  k57andes.*lambdaxgxl.*lambdaygzl+k58andes.*lambdaygxl.*lambdaygzl+ ...
  k47dkt.*lambdazgxl.*lambdazgzl;
[Keg914]=k47andes.*lambdaxgyl.*lambdaxgzl+k48andes.*lambdaxgzl.*lambdaygyl+ ...
  k57andes.*lambdaxgyl.*lambdaygzl+k58andes.*lambdaygyl.*lambdaygzl+ ...
  k47dkt.*lambdazgyl.*lambdazgzl;
[Keg915]=k47andes.*lambdaxgzl.^2+lambdaygzl.*((k48andes+k57andes).*lambdaxgzl+ ...
  k58andes.*lambdaygzl)+k47dkt.*lambdazgzl.^2;
[Keg916]=k49andes.*lambdaxgzl.*lambdazgxl+k59andes.*lambdaygzl.*lambdazgxl+ ...
  k48dkt.*lambdaxgxl.*lambdazgzl+k49dkt.*lambdaygxl.*lambdazgzl;
[Keg917]=k49andes.*lambdaxgzl.*lambdazgyl+k59andes.*lambdaygzl.*lambdazgyl+ ...
  k48dkt.*lambdaxgyl.*lambdazgzl+k49dkt.*lambdaygyl.*lambdazgzl;
[Keg918]=((k48dkt+k49andes).*lambdaxgzl+(k49dkt+k59andes).*lambdaygzl).* ...
  lambdazgzl;
[Keg99]=k44andes.*lambdaxgzl.^2+2.*k45andes.*lambdaxgzl.*lambdaygzl+k55andes.* ...
  lambdaygzl.^2+k44dkt.*lambdazgzl.^2;

%% 
% Assembly the contributions of elements to the global system

ks=sparse(N*np,N*np);


%% ENSAMBLE %%

    ks=ks+sparse(LM(1,:),LM(2,:),Keg12,N*np,N*np);
    ks=ks+sparse(LM(1,:),LM(3,:),Keg13,N*np,N*np);
    ks=ks+sparse(LM(1,:),LM(4,:),Keg14,N*np,N*np);
    ks=ks+sparse(LM(1,:),LM(5,:),Keg15,N*np,N*np);
    ks=ks+sparse(LM(1,:),LM(6,:),Keg16,N*np,N*np);
    ks=ks+sparse(LM(1,:),LM(7,:),Keg17,N*np,N*np);
    ks=ks+sparse(LM(1,:),LM(8,:),Keg18,N*np,N*np);
    ks=ks+sparse(LM(1,:),LM(9,:),Keg19,N*np,N*np);
    ks=ks+sparse(LM(1,:),LM(10,:),Keg110,N*np,N*np); 
    ks=ks+sparse(LM(1,:),LM(11,:),Keg111,N*np,N*np); 
    ks=ks+sparse(LM(1,:),LM(12,:),Keg112,N*np,N*np);
    ks=ks+sparse(LM(1,:),LM(13,:),Keg113,N*np,N*np);    
    ks=ks+sparse(LM(1,:),LM(14,:),Keg114,N*np,N*np);  
    ks=ks+sparse(LM(1,:),LM(15,:),Keg115,N*np,N*np);
    ks=ks+sparse(LM(1,:),LM(16,:),Keg116,N*np,N*np);  
    ks=ks+sparse(LM(1,:),LM(17,:),Keg117,N*np,N*np);
    ks=ks+sparse(LM(1,:),LM(18,:),Keg118,N*np,N*np);
    
    ks=ks+sparse(LM(2,:),LM(3,:),Keg23,N*np,N*np);
    ks=ks+sparse(LM(2,:),LM(4,:),Keg24,N*np,N*np);
    ks=ks+sparse(LM(2,:),LM(5,:),Keg25,N*np,N*np);
    ks=ks+sparse(LM(2,:),LM(6,:),Keg26,N*np,N*np);
    ks=ks+sparse(LM(2,:),LM(7,:),Keg27,N*np,N*np);
    ks=ks+sparse(LM(2,:),LM(8,:),Keg28,N*np,N*np);
    ks=ks+sparse(LM(2,:),LM(9,:),Keg29,N*np,N*np);
    ks=ks+sparse(LM(2,:),LM(10,:),Keg210,N*np,N*np); 
    ks=ks+sparse(LM(2,:),LM(11,:),Keg211,N*np,N*np); 
    ks=ks+sparse(LM(2,:),LM(12,:),Keg212,N*np,N*np);
    ks=ks+sparse(LM(2,:),LM(13,:),Keg213,N*np,N*np);    
    ks=ks+sparse(LM(2,:),LM(14,:),Keg214,N*np,N*np);  
    ks=ks+sparse(LM(2,:),LM(15,:),Keg215,N*np,N*np);
    ks=ks+sparse(LM(2,:),LM(16,:),Keg216,N*np,N*np);    
    ks=ks+sparse(LM(2,:),LM(17,:),Keg217,N*np,N*np);    
    ks=ks+sparse(LM(2,:),LM(18,:),Keg218,N*np,N*np);    
    
    ks=ks+sparse(LM(3,:),LM(4,:),Keg34,N*np,N*np);
    ks=ks+sparse(LM(3,:),LM(5,:),Keg35,N*np,N*np);
    ks=ks+sparse(LM(3,:),LM(6,:),Keg36,N*np,N*np);
    ks=ks+sparse(LM(3,:),LM(7,:),Keg37,N*np,N*np);
    ks=ks+sparse(LM(3,:),LM(8,:),Keg38,N*np,N*np);
    ks=ks+sparse(LM(3,:),LM(9,:),Keg39,N*np,N*np);
    ks=ks+sparse(LM(3,:),LM(10,:),Keg310,N*np,N*np); 
    ks=ks+sparse(LM(3,:),LM(11,:),Keg311,N*np,N*np); 
    ks=ks+sparse(LM(3,:),LM(12,:),Keg312,N*np,N*np);
    ks=ks+sparse(LM(3,:),LM(13,:),Keg313,N*np,N*np);    
    ks=ks+sparse(LM(3,:),LM(14,:),Keg314,N*np,N*np);  
    ks=ks+sparse(LM(3,:),LM(15,:),Keg315,N*np,N*np);
    ks=ks+sparse(LM(3,:),LM(16,:),Keg316,N*np,N*np);    
    ks=ks+sparse(LM(3,:),LM(17,:),Keg317,N*np,N*np);    
    ks=ks+sparse(LM(3,:),LM(18,:),Keg318,N*np,N*np);
    
    ks=ks+sparse(LM(4,:),LM(5,:),Keg45,N*np,N*np);
    ks=ks+sparse(LM(4,:),LM(6,:),Keg46,N*np,N*np);
    ks=ks+sparse(LM(4,:),LM(7,:),Keg47,N*np,N*np);
    ks=ks+sparse(LM(4,:),LM(8,:),Keg48,N*np,N*np);
    ks=ks+sparse(LM(4,:),LM(9,:),Keg49,N*np,N*np);
    ks=ks+sparse(LM(4,:),LM(10,:),Keg410,N*np,N*np); 
    ks=ks+sparse(LM(4,:),LM(11,:),Keg411,N*np,N*np); 
    ks=ks+sparse(LM(4,:),LM(12,:),Keg412,N*np,N*np);
    ks=ks+sparse(LM(4,:),LM(13,:),Keg413,N*np,N*np);    
    ks=ks+sparse(LM(4,:),LM(14,:),Keg414,N*np,N*np);  
    ks=ks+sparse(LM(4,:),LM(15,:),Keg415,N*np,N*np);
    ks=ks+sparse(LM(4,:),LM(16,:),Keg416,N*np,N*np);    
    ks=ks+sparse(LM(4,:),LM(17,:),Keg417,N*np,N*np);    
    ks=ks+sparse(LM(4,:),LM(18,:),Keg418,N*np,N*np);    
    
    ks=ks+sparse(LM(5,:),LM(6,:),Keg56,N*np,N*np);
    ks=ks+sparse(LM(5,:),LM(7,:),Keg57,N*np,N*np);
    ks=ks+sparse(LM(5,:),LM(8,:),Keg58,N*np,N*np);
    ks=ks+sparse(LM(5,:),LM(9,:),Keg59,N*np,N*np);
    ks=ks+sparse(LM(5,:),LM(10,:),Keg510,N*np,N*np); 
    ks=ks+sparse(LM(5,:),LM(11,:),Keg511,N*np,N*np); 
    ks=ks+sparse(LM(5,:),LM(12,:),Keg512,N*np,N*np);
    ks=ks+sparse(LM(5,:),LM(13,:),Keg513,N*np,N*np);    
    ks=ks+sparse(LM(5,:),LM(14,:),Keg514,N*np,N*np);  
    ks=ks+sparse(LM(5,:),LM(15,:),Keg515,N*np,N*np);
    ks=ks+sparse(LM(5,:),LM(16,:),Keg516,N*np,N*np);    
    ks=ks+sparse(LM(5,:),LM(17,:),Keg517,N*np,N*np);
    ks=ks+sparse(LM(5,:),LM(18,:),Keg518,N*np,N*np);
    
    ks=ks+sparse(LM(6,:),LM(7,:),Keg67,N*np,N*np);
    ks=ks+sparse(LM(6,:),LM(8,:),Keg68,N*np,N*np);
    ks=ks+sparse(LM(6,:),LM(9,:),Keg69,N*np,N*np);
    ks=ks+sparse(LM(6,:),LM(10,:),Keg610,N*np,N*np); 
    ks=ks+sparse(LM(6,:),LM(11,:),Keg611,N*np,N*np); 
    ks=ks+sparse(LM(6,:),LM(12,:),Keg612,N*np,N*np);
    ks=ks+sparse(LM(6,:),LM(13,:),Keg613,N*np,N*np);    
    ks=ks+sparse(LM(6,:),LM(14,:),Keg614,N*np,N*np);  
    ks=ks+sparse(LM(6,:),LM(15,:),Keg615,N*np,N*np);
    ks=ks+sparse(LM(6,:),LM(16,:),Keg616,N*np,N*np);
    ks=ks+sparse(LM(6,:),LM(17,:),Keg617,N*np,N*np);
    ks=ks+sparse(LM(6,:),LM(18,:),Keg618,N*np,N*np);
    
    ks=ks+sparse(LM(7,:),LM(8,:),Keg78,N*np,N*np);
    ks=ks+sparse(LM(7,:),LM(9,:),Keg79,N*np,N*np);
    ks=ks+sparse(LM(7,:),LM(10,:),Keg710,N*np,N*np); 
    ks=ks+sparse(LM(7,:),LM(11,:),Keg711,N*np,N*np); 
    ks=ks+sparse(LM(7,:),LM(12,:),Keg712,N*np,N*np);
    ks=ks+sparse(LM(7,:),LM(13,:),Keg713,N*np,N*np);    
    ks=ks+sparse(LM(7,:),LM(14,:),Keg714,N*np,N*np);  
    ks=ks+sparse(LM(7,:),LM(15,:),Keg715,N*np,N*np);
    ks=ks+sparse(LM(7,:),LM(16,:),Keg716,N*np,N*np);
    ks=ks+sparse(LM(7,:),LM(17,:),Keg717,N*np,N*np);
    ks=ks+sparse(LM(7,:),LM(18,:),Keg718,N*np,N*np);
    
    
    ks=ks+sparse(LM(8,:),LM(9,:),Keg89,N*np,N*np);
    ks=ks+sparse(LM(8,:),LM(10,:),Keg810,N*np,N*np); 
    ks=ks+sparse(LM(8,:),LM(11,:),Keg811,N*np,N*np); 
    ks=ks+sparse(LM(8,:),LM(12,:),Keg812,N*np,N*np);
    ks=ks+sparse(LM(8,:),LM(13,:),Keg813,N*np,N*np);    
    ks=ks+sparse(LM(8,:),LM(14,:),Keg814,N*np,N*np);  
    ks=ks+sparse(LM(8,:),LM(15,:),Keg815,N*np,N*np);
    ks=ks+sparse(LM(8,:),LM(16,:),Keg816,N*np,N*np);    
    ks=ks+sparse(LM(8,:),LM(17,:),Keg817,N*np,N*np);    
    ks=ks+sparse(LM(8,:),LM(18,:),Keg818,N*np,N*np);    
    
    
    ks=ks+sparse(LM(9,:),LM(10,:),Keg910,N*np,N*np); 
    ks=ks+sparse(LM(9,:),LM(11,:),Keg911,N*np,N*np); 
    ks=ks+sparse(LM(9,:),LM(12,:),Keg912,N*np,N*np);
    ks=ks+sparse(LM(9,:),LM(13,:),Keg913,N*np,N*np);    
    ks=ks+sparse(LM(9,:),LM(14,:),Keg914,N*np,N*np);  
    ks=ks+sparse(LM(9,:),LM(15,:),Keg915,N*np,N*np);
    ks=ks+sparse(LM(9,:),LM(16,:),Keg916,N*np,N*np);
    ks=ks+sparse(LM(9,:),LM(17,:),Keg917,N*np,N*np);
    ks=ks+sparse(LM(9,:),LM(18,:),Keg918,N*np,N*np);
    
    
    ks=ks+sparse(LM(10,:),LM(11,:),Keg1011,N*np,N*np); 
    ks=ks+sparse(LM(10,:),LM(12,:),Keg1012,N*np,N*np);
    ks=ks+sparse(LM(10,:),LM(13,:),Keg1013,N*np,N*np);    
    ks=ks+sparse(LM(10,:),LM(14,:),Keg1014,N*np,N*np);  
    ks=ks+sparse(LM(10,:),LM(15,:),Keg1015,N*np,N*np);
    ks=ks+sparse(LM(10,:),LM(16,:),Keg1016,N*np,N*np);
    ks=ks+sparse(LM(10,:),LM(17,:),Keg1017,N*np,N*np);
    ks=ks+sparse(LM(10,:),LM(18,:),Keg1018,N*np,N*np);
    
    
    ks=ks+sparse(LM(11,:),LM(12,:),Keg1112,N*np,N*np);
    ks=ks+sparse(LM(11,:),LM(13,:),Keg1113,N*np,N*np);    
    ks=ks+sparse(LM(11,:),LM(14,:),Keg1114,N*np,N*np);  
    ks=ks+sparse(LM(11,:),LM(15,:),Keg1115,N*np,N*np);
    ks=ks+sparse(LM(11,:),LM(16,:),Keg1116,N*np,N*np);
    ks=ks+sparse(LM(11,:),LM(17,:),Keg1117,N*np,N*np);
    ks=ks+sparse(LM(11,:),LM(18,:),Keg1118,N*np,N*np);
    
    
    ks=ks+sparse(LM(12,:),LM(13,:),Keg1213,N*np,N*np);    
    ks=ks+sparse(LM(12,:),LM(14,:),Keg1214,N*np,N*np);  
    ks=ks+sparse(LM(12,:),LM(15,:),Keg1215,N*np,N*np);
    ks=ks+sparse(LM(12,:),LM(16,:),Keg1216,N*np,N*np);
    ks=ks+sparse(LM(12,:),LM(17,:),Keg1217,N*np,N*np);
    ks=ks+sparse(LM(12,:),LM(18,:),Keg1218,N*np,N*np);
    
    
    ks=ks+sparse(LM(13,:),LM(14,:),Keg1314,N*np,N*np);  
    ks=ks+sparse(LM(13,:),LM(15,:),Keg1315,N*np,N*np);
    ks=ks+sparse(LM(13,:),LM(16,:),Keg1316,N*np,N*np);
    ks=ks+sparse(LM(13,:),LM(17,:),Keg1317,N*np,N*np);
    ks=ks+sparse(LM(13,:),LM(18,:),Keg1318,N*np,N*np);

    
    ks=ks+sparse(LM(14,:),LM(15,:),Keg1415,N*np,N*np);
    ks=ks+sparse(LM(14,:),LM(16,:),Keg1416,N*np,N*np);    
    ks=ks+sparse(LM(14,:),LM(17,:),Keg1417,N*np,N*np);    
    ks=ks+sparse(LM(14,:),LM(18,:),Keg1418,N*np,N*np);    
    
    ks=ks+sparse(LM(15,:),LM(16,:),Keg1516,N*np,N*np);
    ks=ks+sparse(LM(15,:),LM(17,:),Keg1517,N*np,N*np);
    ks=ks+sparse(LM(15,:),LM(18,:),Keg1518,N*np,N*np);    
    
    ks=ks+sparse(LM(16,:),LM(17,:),Keg1617,N*np,N*np);
    ks=ks+sparse(LM(16,:),LM(18,:),Keg1618,N*np,N*np);

    ks=ks+sparse(LM(17,:),LM(18,:),Keg1718,N*np,N*np);
    
    ks=ks+ks.';
    
    ks=ks+sparse(LM(1,:),LM(1,:),Keg11,N*np,N*np);
    ks=ks+sparse(LM(2,:),LM(2,:),Keg22,N*np,N*np);
    ks=ks+sparse(LM(3,:),LM(3,:),Keg33,N*np,N*np);
    ks=ks+sparse(LM(4,:),LM(4,:),Keg44,N*np,N*np);
    ks=ks+sparse(LM(5,:),LM(5,:),Keg55,N*np,N*np);
    ks=ks+sparse(LM(6,:),LM(6,:),Keg66,N*np,N*np);
    ks=ks+sparse(LM(7,:),LM(7,:),Keg77,N*np,N*np);
    ks=ks+sparse(LM(8,:),LM(8,:),Keg88,N*np,N*np);
    ks=ks+sparse(LM(9,:),LM(9,:),Keg99,N*np,N*np);
    ks=ks+sparse(LM(10,:),LM(10,:),Keg1010,N*np,N*np);
    ks=ks+sparse(LM(11,:),LM(11,:),Keg1111,N*np,N*np);
    ks=ks+sparse(LM(12,:),LM(12,:),Keg1212,N*np,N*np);
    ks=ks+sparse(LM(13,:),LM(13,:),Keg1313,N*np,N*np);
    ks=ks+sparse(LM(14,:),LM(14,:),Keg1414,N*np,N*np);
    ks=ks+sparse(LM(15,:),LM(15,:),Keg1515,N*np,N*np);
    ks=ks+sparse(LM(16,:),LM(16,:),Keg1616,N*np,N*np);
    ks=ks+sparse(LM(17,:),LM(17,:),Keg1717,N*np,N*np);    
    ks=ks+sparse(LM(18,:),LM(18,:),Keg1818,N*np,N*np);   

%%

end

